openapi: 3.2.0
info:
  version: v4.28.3
  description: '# API specification


    This documentation describes the data resources and technical details available for the RELEX Data API.'
  title: RELEX Data API for Example Customer Metadata API
  contact:
    email: support@relexsolutions.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: assets/logo.png
    backgroundColor: '#FFFFFF'
    altText: RELEX Logo
servers:
- url: https://uat-eu.rest.relexsolutions.com/restapi-test
- url: https://eu.rest.relexsolutions.com/restapi-test
security:
- OAuth2: []
tags:
- name: Metadata
  description: The namespace for metadata contains the different endpoints for API metadata.
paths:
  /meta/version:
    get:
      tags:
      - Metadata
      summary: Version
      description: HTTP GET handler for version endpoint
      operationId: GetVersion
      parameters:
      - $ref: '#/components/parameters/HttpHeader'
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/version'
        '400':
          $ref: '#/components/responses/Problem400Response'
        '401':
          $ref: '#/components/responses/Problem401Response'
        '403':
          $ref: '#/components/responses/Problem403Response'
        '404':
          $ref: '#/components/responses/Problem404Response'
        '413':
          $ref: '#/components/responses/Problem413Response'
        '429':
          $ref: '#/components/responses/Problem429Response'
        5XX:
          $ref: '#/components/responses/Problem5xxResponse'
  /meta/errors:
    get:
      tags:
      - Metadata
      summary: Errors
      description: HTTP GET handler for errors endpoint
      operationId: GetErrors
      parameters:
      - $ref: '#/components/parameters/request_id'
      - $ref: '#/components/parameters/start_timestamp'
      - $ref: '#/components/parameters/end_timestamp'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/per_page'
      - $ref: '#/components/parameters/HttpHeader'
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errors'
        '400':
          $ref: '#/components/responses/Problem400Response'
        '401':
          $ref: '#/components/responses/Problem401Response'
        '403':
          $ref: '#/components/responses/Problem403Response'
        '404':
          $ref: '#/components/responses/Problem404Response'
        '413':
          $ref: '#/components/responses/Problem413Response'
        '429':
          $ref: '#/components/responses/Problem429Response'
        5XX:
          $ref: '#/components/responses/Problem5xxResponse'
  /meta/health:
    get:
      tags:
      - Metadata
      summary: Health
      description: HTTP GET handler for health endpoint
      operationId: GetHealth
      parameters:
      - $ref: '#/components/parameters/HttpHeader'
      responses:
        '200':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/health'
        '400':
          $ref: '#/components/responses/Problem400Response'
        '401':
          $ref: '#/components/responses/Problem401Response'
        '403':
          $ref: '#/components/responses/Problem403Response'
        '404':
          $ref: '#/components/responses/Problem404Response'
        '413':
          $ref: '#/components/responses/Problem413Response'
        '429':
          $ref: '#/components/responses/Problem429Response'
        5XX:
          $ref: '#/components/responses/Problem5xxResponse'
components:
  responses:
    Problem5xxResponse:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/500
            title: An internal error occurred.
            status: 500
            detail: The server is unable to process the request.
    Problem401Response:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/401
            title: Unauthorized
            status: 401
    Problem429Response:
      description: Too Many Requests
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/429
            title: Too Many Requests
            status: 429
            detail: 'Rate limit has been exceeded: The request could not be completed due to the client exceeding the request limit.'
    Problem413Response:
      description: Content Too Large
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/413
            title: Payload Too Large
            status: 413
            detail: Payload was larger than 1mb
    Problem404Response:
      description: Page Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/404
            title: Page Not Found
            status: 404
    Problem403Response:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_general'
          example:
            type: https://relexsolutions.com/rest/errors/403
            title: Forbidden
            status: 403
    Problem400Response:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/problem_details_400'
  schemas:
    errors:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                format: uuid
                description: Unique message identifier
                example: 377f84f0-2f74-11ed-a261-0242ac120002
              model:
                type: string
                description: Type of record
                example: product-location
              identifier:
                type: object
                description: Record Identifier
                example:
                  product_code: foo
                  location_code: bar
              record:
                type: object
                description: A complete record, which caused an error
                example:
                  product_code: foo
                  location_code: bar
              error:
                type: object
                description: Object with error details
                properties:
                  type:
                    type: string
                    description: Machine-readable error message
                    example: EnricherError
                  description:
                    type: string
                    description: Human-readable error message
                    example: Could not find a match for product_code 'FOO2'
                additionalProperties: false
              event_timestamp:
                type: string
                description: The event timestamp
                format: date-time
                example: '2022-08-21T09:11:08+00:00'
              ingestion_timestamp:
                type: string
                description: The message ingestion timestamp
                format: date-time
                example: '2022-08-21T09:11:08+00:00'
              source:
                type: string
                description: Identifier of a system where event was generated
                example: RELEX Plan
              batch_id:
                type: string
                description: A unique identifier assigned to a batch of events
                format: uuid
                example: d64be281-3470-411a-9235-9e15c7b500b8
              request_id:
                type: string
                description: A unique identifier assigned to a request
                format: uuid
                example: c88ca2da-5e77-4f63-bbee-61df9edf591f
            additionalProperties: false
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: /errors?request_id=d64be281-3470-411a-9235-9e15c7b500b8
              additionalProperties: false
            next:
              type: object
              properties:
                href:
                  type: string
                  example: /errors?request_id=d64be281-3470-411a-9235-9e15c7b500b8&page=2
              additionalProperties: false
          additionalProperties: false
      additionalProperties: false
      $schema: https://json-schema.org/draft/2020-12/schema
    health:
      type: object
      properties:
        meta:
          type: object
          properties:
            code:
              type: number
              description: HTTP response code
              example: 200
            message:
              type: string
              description: HTTP response message
              example: OK
        data:
          type: object
      $schema: https://json-schema.org/draft/2020-12/schema
      additionalProperties: false
    version:
      type: object
      properties:
        meta:
          type: object
          properties:
            code:
              type: number
              description: HTTP response code
              example: 200
            message:
              type: string
              description: HTTP response message
              example: OK
        data:
          type: object
          properties:
            api_version:
              type: string
              description: API version according to OpenAPI specification
              example: v2.7.7-prelease
            core_version:
              type: string
              description: Version number including core dependencies of REST API
              example: v1.2.3
            data_version:
              type: string
              description: Data model version
              example: v3.2.1
      $schema: https://json-schema.org/draft/2020-12/schema
    problem_details_general:
      description: Implementation of [RFC7807](https://tools.ietf.org/html/rfc7807) Problem Details object.  Content type should always be ```application/problem+json```.  Problem type definitions MAY extend the problem details object with additional members
      type: object
      required:
      - type
      - title
      - status
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type.
          type: string
          format: uri
          example: https://relexsolutions.com/issue
        title:
          description: A short, human-readable summary of the problem type.
          type: string
          example: Bad Request
        status:
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          type: number
          example: 400
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
    problem_details_400:
      description: Implementation of [RFC7807](https://tools.ietf.org/html/rfc7807) Problem Details object.  Content type should always be ```application/problem+json```.  Problem type definitions MAY extend the problem details object with additional members
      type: object
      required:
      - type
      - title
      - status
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type.
          type: string
          format: uri
          example: https://relexsolutions.com/rest/errors/400
        title:
          description: A short, human-readable summary of the problem type.
          type: string
          example: Bad Request
        status:
          description: The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
          type: number
          example: 400
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: validating the payload's JSON schema failed
        debugging:
          description: Debugging information for DEV and QA environments.
          type: string
        validation_errors:
          type: array
          description: A list of issues that exist with the request.
          items:
            type: object
            properties:
              location:
                type: string
              message:
                type: string
              violation:
                type: string
          example:
          - location: /data/0
            message: 'missing properties: ''code'''
            violation: required
          - location: /meta/example
            message: expected string, but got number
            violation: type
  parameters:
    start_timestamp:
      description: Start timestamp (inclusive), required unless request_id is specified
      in: query
      name: start_timestamp
      example: '2023-06-13T00:00:00.000Z'
      schema:
        format: date-time
        type: string
    end_timestamp:
      description: End timestamp (inclusive), required unless request_id is specified
      in: query
      name: end_timestamp
      example: '2023-06-14T12:34:56.999Z'
      schema:
        format: date-time
        type: string
    request_id:
      description: Request ID, required unless timestamp parameters are specified
      in: query
      name: request_id
      example: c88ca2da-5e77-4f63-bbee-61df9edf591f
      schema:
        format: uuid
        type: string
    page:
      description: Page number, 1-based
      in: query
      name: page
      example: 1
      schema:
        type: integer
        default: 1
    per_page:
      description: Number of records per page
      in: query
      name: per_page
      example: 5
      schema:
        type: integer
        default: 500
        maximum: 10000
    HttpHeader:
      in: header
      name: Content-Type
      description: The media type in the Content-Type header must be specified and must be _application/json_. The character encoding of the data is expected to be UTF-8.
      required: true
      example: application/json
      schema:
        type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      description: The RELEX Data API uses OAuth 2 with the client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: https://identity.prod-eu.prod.cc.relexsolutions.com/login/restapi_prod/connect/token
          scopes:
            openid_api: Internal use
x-tagGroups:
- name: Endpoints
  tags:
  - Metadata
  - Master data
  - Transactions
  - Custom
- name: Customizations
  tags:
  - Customizations
